name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello Thanks for reaching out i will respond as fast as i can'
        pr-message: 'Thanks For your time i will review your request as fast as i can'
